// Generates web/abi.js: the function selectors, event topics and custom-error table the playground page needs. The page
// has no build step and no dependencies, so the hashes are computed here instead of by hand. Errors are read from the
// templates' own `sol!` blocks, so a renamed or added error shows up in the page's messages automatically.
//
//   node e2e/gen-web-abi.mjs           # write web/abi.js
//   node e2e/gen-web-abi.mjs --check   # fail if web/abi.js is out of date (CI)
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { toEventSelector, toFunctionSelector } from "viem";

const root = new URL("../", import.meta.url);
const out = new URL("web/abi.js", root);

// The calls the page makes, by contract. The playground panels mirror the escrow's rules themselves (an older escrow had no
// canRelease / canRefund); the agent demo reads the stream like the agent does, which the current Sepolia stream supports.
const FUNCTIONS = {
  token: {
    balanceOf: "balanceOf(address)", allowance: "allowance(address,address)", approve: "approve(address,uint256)",
    decimals: "decimals()", symbol: "symbol()",
  },
  faucet: { drip: "drip()", availableAt: "availableAt(address)", amount: "amount()", cooldown: "cooldown()" },
  stream: {
    create: "create(address,uint256,uint256,uint256)", withdraw: "withdraw(uint256)", cancel: "cancel(uint256)",
    stream: "stream(uint256)", streamCount: "streamCount()",
    token: "token()", streamed: "streamed(uint256)", withdrawable: "withdrawable(uint256)",
    previewCancel: "previewCancel(uint256)", claimable: "claimable(address)",
  },
  escrow: {
    create: "create(address,uint256,uint256,address)", release: "release(uint256)", refund: "refund(uint256)",
    deal: "deal(uint256)", dealCount: "dealCount()",
  },
  vault: { deposit: "deposit(uint256)", withdraw: "withdraw(uint256)", depositOf: "depositOf(address)", totalDeposits: "totalDeposits()" },
};
const EVENTS = {
  StreamCreated: "StreamCreated(uint256,address,address,uint256,uint256,uint256)",
  DealCreated: "DealCreated(uint256,address,address,uint256,uint256)",
  Withdrawn: "Withdrawn(uint256,address,uint256)",
  Cancelled: "Cancelled(uint256,uint256,uint256)",
  PaymentHeld: "PaymentHeld(address,uint256)",
};

const errors = {};
const templates = new URL("templates/", root);
for (const t of readdirSync(templates).filter((d) => !d.startsWith("_")).sort()) {
  const lib = readFileSync(new URL(`${t}/src/lib.rs`, templates), "utf8");
  for (const [, name, params] of lib.matchAll(/^\s*error (\w+)\(([^)]*)\);/gm)) {
    const fields = params.split(",").map((p) => p.trim()).filter(Boolean).map((p) => p.split(/\s+/));
    const types = fields.map(([type]) => type);
    errors[toFunctionSelector(`${name}(${types.join(",")})`)] = { name, types, names: fields.map(([, n]) => n ?? "") };
  }
}

// The agent's own hint for each error code, from the agent kit, so the page's agent demo returns the same hints.
const kit = readFileSync(new URL("templates/_client/_agent/agent-kit.ts", root), "utf8");
const hintBlock = /const HINTS: Record<string, string> = \{\n([\s\S]*?)\n\};/.exec(kit);
if (!hintBlock) throw new Error("HINTS not found in agent-kit.ts");
const agentHints = {};
for (const line of hintBlock[1].split("\n")) {
  const m = /^\s*(\w+): "((?:[^"\\]|\\.)*)",$/.exec(line);
  if (!m) throw new Error(`unexpected line in agent-kit.ts HINTS: ${line}`);
  agentHints[m[1]] = JSON.parse(`"${m[2]}"`);
}

const sel = Object.fromEntries(
  Object.entries(FUNCTIONS).map(([c, fns]) => [c, Object.fromEntries(Object.entries(fns).map(([k, sig]) => [k, toFunctionSelector(sig)]))]),
);
const topics = Object.fromEntries(Object.entries(EVENTS).map(([k, sig]) => [k, toEventSelector(sig)]));
const sortedErrors = Object.fromEntries(Object.entries(errors).sort(([a], [b]) => a.localeCompare(b)));

const text = `// Generated by e2e/gen-web-abi.mjs from the templates. Do not edit: run \`node e2e/gen-web-abi.mjs\` (CI checks it is current).
const ABI = ${JSON.stringify({ sel, topics, errors: sortedErrors, agentHints }, null, 2)};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== text) {
    console.error("web/abi.js is out of date. Run: node e2e/gen-web-abi.mjs");
    process.exit(1);
  }
  console.log("web/abi.js is up to date");
} else {
  writeFileSync(out, text);
  console.log(`wrote web/abi.js: ${Object.keys(sortedErrors).length} errors, ${Object.values(sel).reduce((n, c) => n + Object.keys(c).length, 0)} functions`);
}
