// Generates web/abi.js: the function selectors, event topics and custom-error table the playground page needs. The page
// has no build step and no dependencies, so the hashes are computed here instead of by hand. Errors are read from the
// templates' own `sol!` blocks, so a renamed or added error shows up in the page's messages automatically.
//
//   node e2e/gen-web-abi.mjs           # write web/abi.js
//   node e2e/gen-web-abi.mjs --check   # fail if web/abi.js is out of date (CI)
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { toEventSelector, toFunctionSelector } from "viem";

const root = new URL("../", import.meta.url);
const out = new URL("web/abi.js", root);

// The calls the page makes, by contract. Only functions every deployed version has: the live Sepolia stream and escrow
// predate previewCancel / canRelease / canRefund, so the page mirrors those rules itself.
const FUNCTIONS = {
  token: { balanceOf: "balanceOf(address)", allowance: "allowance(address,address)", approve: "approve(address,uint256)" },
  faucet: { drip: "drip()", availableAt: "availableAt(address)", amount: "amount()", cooldown: "cooldown()" },
  stream: {
    create: "create(address,uint256,uint256,uint256)", withdraw: "withdraw(uint256)", cancel: "cancel(uint256)",
    stream: "stream(uint256)", streamCount: "streamCount()",
  },
  escrow: {
    create: "create(address,uint256,uint256,address)", release: "release(uint256)", refund: "refund(uint256)",
    deal: "deal(uint256)", dealCount: "dealCount()",
  },
  vault: { deposit: "deposit(uint256)", withdraw: "withdraw(uint256)", depositOf: "depositOf(address)", totalDeposits: "totalDeposits()" },
};
const EVENTS = {
  StreamCreated: "StreamCreated(uint256,address,address,uint256,uint256,uint256)",
  DealCreated: "DealCreated(uint256,address,address,uint256,uint256)",
};

const errors = {};
const templates = new URL("templates/", root);
for (const t of readdirSync(templates).filter((d) => !d.startsWith("_")).sort()) {
  const lib = readFileSync(new URL(`${t}/src/lib.rs`, templates), "utf8");
  for (const [, name, params] of lib.matchAll(/^\s*error (\w+)\(([^)]*)\);/gm)) {
    const fields = params.split(",").map((p) => p.trim()).filter(Boolean).map((p) => p.split(/\s+/));
    const types = fields.map(([type]) => type);
    errors[toFunctionSelector(`${name}(${types.join(",")})`)] = { name, types, names: fields.map(([, n]) => n ?? "") };
  }
}

const sel = Object.fromEntries(
  Object.entries(FUNCTIONS).map(([c, fns]) => [c, Object.fromEntries(Object.entries(fns).map(([k, sig]) => [k, toFunctionSelector(sig)]))]),
);
const topics = Object.fromEntries(Object.entries(EVENTS).map(([k, sig]) => [k, toEventSelector(sig)]));
const sortedErrors = Object.fromEntries(Object.entries(errors).sort(([a], [b]) => a.localeCompare(b)));

const text = `// Generated by e2e/gen-web-abi.mjs from the templates. Do not edit: run \`node e2e/gen-web-abi.mjs\` (CI checks it is current).
const ABI = ${JSON.stringify({ sel, topics, errors: sortedErrors }, null, 2)};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(out, "utf8");
  } catch {}
  if (current !== text) {
    console.error("web/abi.js is out of date. Run: node e2e/gen-web-abi.mjs");
    process.exit(1);
  }
  console.log("web/abi.js is up to date");
} else {
  writeFileSync(out, text);
  console.log(`wrote web/abi.js: ${Object.keys(sortedErrors).length} errors, ${Object.values(sel).reduce((n, c) => n + Object.keys(c).length, 0)} functions`);
}
