// Generated by e2e/gen-web-abi.mjs from the templates. Do not edit: run `node e2e/gen-web-abi.mjs` (CI checks it is current).
const ABI = {
  "sel": {
    "token": {
      "balanceOf": "0x70a08231",
      "allowance": "0xdd62ed3e",
      "approve": "0x095ea7b3",
      "decimals": "0x313ce567",
      "symbol": "0x95d89b41"
    },
    "faucet": {
      "drip": "0x9f678cca",
      "availableAt": "0xabb2e533",
      "amount": "0xaa8c217c",
      "cooldown": "0x787a08a6"
    },
    "stream": {
      "create": "0x8c71ec16",
      "withdraw": "0x2e1a7d4d",
      "cancel": "0x40e58ee5",
      "stream": "0x2d94d8b5",
      "streamCount": "0x89d0e119",
      "token": "0xfc0c546a",
      "streamed": "0x83496021",
      "withdrawable": "0xf11988e0",
      "previewCancel": "0x21575e57",
      "claimable": "0x402914f5"
    },
    "escrow": {
      "create": "0xa5d048d3",
      "release": "0x37bdc99b",
      "refund": "0x278ecde1",
      "deal": "0xc959c42b",
      "dealCount": "0xeadb3c9c"
    },
    "vault": {
      "deposit": "0xb6b55f25",
      "withdraw": "0x2e1a7d4d",
      "depositOf": "0x23e3fbd5",
      "totalDeposits": "0x7d882097"
    }
  },
  "topics": {
    "StreamCreated": "0x8d3a4d9a98c71920c13665fb97f1a612978391e661f9a17fa5390f60e7424d5c",
    "DealCreated": "0x584834bba667bf1cd5aa00cfe8042067a3d6b5da7b1a555dc640e003ea7328df",
    "Withdrawn": "0xcf7d23a3cbe4e8b36ff82fd1b05b1b17373dc7804b4ebbd6e2356716ef202372",
    "Cancelled": "0x85880e29de5e2bae8d4c8c1ff6f504e15a1ad0b94b8102feb034e4390ce26a75",
    "PaymentHeld": "0xb337b49a0a0417e3c488bc7b1cb858e1eaabaa2f20420846aaec104fa6330855"
  },
  "errors": {
    "0x045c4b02": {
      "name": "TokenTransferFailed",
      "types": [],
      "names": []
    },
    "0x06250401": {
      "name": "AmountTooLarge",
      "types": [],
      "names": []
    },
    "0x0e6fd6e4": {
      "name": "DeadlineInPast",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "deadline",
        "now"
      ]
    },
    "0x155eed36": {
      "name": "NothingToWithdraw",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x177e802f": {
      "name": "ERC721InsufficientApproval",
      "types": [
        "address",
        "uint256"
      ],
      "names": [
        "operator",
        "tokenId"
      ]
    },
    "0x19ab2d28": {
      "name": "StalePrice",
      "types": [
        "uint256",
        "uint256",
        "uint256"
      ],
      "names": [
        "updatedAt",
        "now",
        "maxAge"
      ]
    },
    "0x1f2a2005": {
      "name": "ZeroAmount",
      "types": [],
      "names": []
    },
    "0x23d359a3": {
      "name": "DivisionByZero",
      "types": [],
      "names": []
    },
    "0x25c3f46e": {
      "name": "InsufficientDeposit",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "have",
        "want"
      ]
    },
    "0x35278d12": {
      "name": "Overflow",
      "types": [],
      "names": []
    },
    "0x35b2186b": {
      "name": "NoSuchStream",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x35be3ac8": {
      "name": "InvalidConfig",
      "types": [],
      "names": []
    },
    "0x361c31f2": {
      "name": "NotMinter",
      "types": [
        "address"
      ],
      "names": [
        "caller"
      ]
    },
    "0x38ee04a7": {
      "name": "InvalidPrice",
      "types": [
        "int256"
      ],
      "names": [
        "answer"
      ]
    },
    "0x4a894b4b": {
      "name": "NoSuchDeal",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x5b08ba18": {
      "name": "ERC721InvalidOperator",
      "types": [
        "address"
      ],
      "names": [
        "operator"
      ]
    },
    "0x5ba9375b": {
      "name": "StartInPast",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "start",
        "now"
      ]
    },
    "0x5f9e667d": {
      "name": "FeedUnavailable",
      "types": [],
      "names": []
    },
    "0x64283d7b": {
      "name": "ERC721IncorrectOwner",
      "types": [
        "address",
        "uint256",
        "address"
      ],
      "names": [
        "sender",
        "tokenId",
        "owner"
      ]
    },
    "0x64a0ae92": {
      "name": "ERC721InvalidReceiver",
      "types": [
        "address"
      ],
      "names": [
        "receiver"
      ]
    },
    "0x6a06b652": {
      "name": "NotFunded",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x6c59da12": {
      "name": "MulDivOverflow",
      "types": [
        "uint256",
        "uint256",
        "uint256"
      ],
      "names": [
        "a",
        "b",
        "denominator"
      ]
    },
    "0x702d6859": {
      "name": "SelfDeal",
      "types": [],
      "names": []
    },
    "0x7258997e": {
      "name": "NotActive",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x7e273289": {
      "name": "ERC721NonexistentToken",
      "types": [
        "uint256"
      ],
      "names": [
        "tokenId"
      ]
    },
    "0x89c62b64": {
      "name": "ERC721InvalidOwner",
      "types": [
        "address"
      ],
      "names": [
        "owner"
      ]
    },
    "0x8ad52bdd": {
      "name": "IncompleteRound",
      "types": [],
      "names": []
    },
    "0x91beda24": {
      "name": "InsufficientAllowance",
      "types": [
        "address",
        "address",
        "uint256",
        "uint256"
      ],
      "names": [
        "owner",
        "spender",
        "have",
        "want"
      ]
    },
    "0x969bf728": {
      "name": "NothingToClaim",
      "types": [],
      "names": []
    },
    "0xa9fbf51f": {
      "name": "ERC721InvalidApprover",
      "types": [
        "address"
      ],
      "names": [
        "approver"
      ]
    },
    "0xbf8157f3": {
      "name": "BadTimeRange",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "start",
        "stop"
      ]
    },
    "0xd92e233d": {
      "name": "ZeroAddress",
      "types": [],
      "names": []
    },
    "0xdb42144d": {
      "name": "InsufficientBalance",
      "types": [
        "address",
        "uint256",
        "uint256"
      ],
      "names": [
        "from",
        "have",
        "want"
      ]
    },
    "0xdd050eb2": {
      "name": "SelfStream",
      "types": [],
      "names": []
    },
    "0xe86f59ea": {
      "name": "TooSoon",
      "types": [
        "uint256"
      ],
      "names": [
        "availableAt"
      ]
    },
    "0xea8e4eb5": {
      "name": "NotAuthorized",
      "types": [],
      "names": []
    }
  },
  "agentHints": {
    "NotAuthorized": "This account is not allowed to do this right now. Check the permission or status intent to see who can.",
    "NothingToWithdraw": "Nothing has been earned since the last withdrawal. Try again later.",
    "InsufficientDeposit": "The account has less than that in the vault. Check get_vault, or withdraw with all: true.",
    "ZeroAmount": "The amount must be greater than zero.",
    "NothingToClaim": "Nothing is held for this account. Check with claim_held_payment and checkOnly, or get_stream's heldForClaim.",
    "NotActive": "This stream was already cancelled.",
    "NotFunded": "This deal was already released or refunded.",
    "NoSuchStream": "No stream has this id.",
    "NoSuchDeal": "No deal has this id.",
    "InsufficientBalance": "The account holds less than that. get_token (or the template's get_ intent) shows its balance.",
    "InsufficientAllowance": "The spender may not take that much from the account. The owner has to approve a larger amount first.",
    "TooSoon": "This account already dripped within the cooldown. get_faucet shows secondsUntilNext.",
    "FaucetEmpty": "The faucet holds less than one drip. Someone has to send it tokens first.",
    "ERC721NonexistentToken": "No token has this id. get_nft shows how many exist; ids start at 1.",
    "ERC721IncorrectOwner": "The agent does not own this token. get_nft with the tokenId shows its owner.",
    "ERC721InsufficientApproval": "The agent is neither the owner nor approved for this token.",
    "ERC721InvalidReceiver": "The recipient is a contract that does not accept NFTs; the token would be stuck there. Send it to an account instead.",
    "NotMinter": "Only the collection's minter may mint. get_nft shows the minter.",
    "DivisionByZero": "The denominator is zero. Pass a non-zero denominator.",
    "MulDivOverflow": "The result does not fit in 256 bits, even though the contract computes the product exactly. Use smaller inputs or a larger denominator.",
    "Overflow": "The result would not fit in 256 bits, so nothing was sent.",
    "StalePrice": "The feed has not updated within maxAge, so its price is not used. Try again later; do not price a payment with it.",
    "InvalidPrice": "The feed reported a zero or negative price, so it is not used. Try again later or use another feed.",
    "IncompleteRound": "The feed's latest round has not completed. Try again shortly.",
    "FeedUnavailable": "The price feed could not be read. Check that the oracle points at a live feed on this chain.",
    "PriceMoved": "The price changed between two reads. Ask again.",
    "StartInPast": "The start time had already passed when the transaction ran. Use a larger startInSeconds.",
    "DeadlineInPast": "The deadline had already passed when the transaction ran. Use a larger deadlineSeconds.",
    "TokenTransferFailed": "The token transfer failed: check the agent's balance and allowance.",
    "OutOfGas": "The transaction used all its gas. Nothing changed on-chain. Retry it, or set a higher GAS_LIMIT."
  }
};
