// Generated by e2e/gen-web-abi.mjs from the templates. Do not edit: run `node e2e/gen-web-abi.mjs` (CI checks it is current).
const ABI = {
  "sel": {
    "token": {
      "balanceOf": "0x70a08231",
      "allowance": "0xdd62ed3e",
      "approve": "0x095ea7b3",
      "decimals": "0x313ce567",
      "symbol": "0x95d89b41"
    },
    "faucet": {
      "drip": "0x9f678cca",
      "availableAt": "0xabb2e533",
      "amount": "0xaa8c217c",
      "cooldown": "0x787a08a6"
    },
    "stream": {
      "create": "0x8c71ec16",
      "withdraw": "0x2e1a7d4d",
      "cancel": "0x40e58ee5",
      "stream": "0x2d94d8b5",
      "streamCount": "0x89d0e119",
      "token": "0xfc0c546a",
      "streamed": "0x83496021",
      "withdrawable": "0xf11988e0",
      "previewCancel": "0x21575e57",
      "claimable": "0x402914f5"
    },
    "escrow": {
      "create": "0xa5d048d3",
      "release": "0x37bdc99b",
      "refund": "0x278ecde1",
      "deal": "0xc959c42b",
      "dealCount": "0xeadb3c9c"
    },
    "vault": {
      "deposit": "0xb6b55f25",
      "withdraw": "0x2e1a7d4d",
      "depositOf": "0x23e3fbd5",
      "totalDeposits": "0x7d882097"
    }
  },
  "topics": {
    "StreamCreated": "0x8d3a4d9a98c71920c13665fb97f1a612978391e661f9a17fa5390f60e7424d5c",
    "DealCreated": "0x584834bba667bf1cd5aa00cfe8042067a3d6b5da7b1a555dc640e003ea7328df",
    "Withdrawn": "0xcf7d23a3cbe4e8b36ff82fd1b05b1b17373dc7804b4ebbd6e2356716ef202372",
    "Cancelled": "0x85880e29de5e2bae8d4c8c1ff6f504e15a1ad0b94b8102feb034e4390ce26a75",
    "PaymentHeld": "0xb337b49a0a0417e3c488bc7b1cb858e1eaabaa2f20420846aaec104fa6330855"
  },
  "errors": {
    "0x045c4b02": {
      "name": "TokenTransferFailed",
      "types": [],
      "names": []
    },
    "0x06250401": {
      "name": "AmountTooLarge",
      "types": [],
      "names": []
    },
    "0x0e6fd6e4": {
      "name": "DeadlineInPast",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "deadline",
        "now"
      ]
    },
    "0x155eed36": {
      "name": "NothingToWithdraw",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x1f2a2005": {
      "name": "ZeroAmount",
      "types": [],
      "names": []
    },
    "0x25c3f46e": {
      "name": "InsufficientDeposit",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "have",
        "want"
      ]
    },
    "0x35b2186b": {
      "name": "NoSuchStream",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x4a894b4b": {
      "name": "NoSuchDeal",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x5ba9375b": {
      "name": "StartInPast",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "start",
        "now"
      ]
    },
    "0x6a06b652": {
      "name": "NotFunded",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x702d6859": {
      "name": "SelfDeal",
      "types": [],
      "names": []
    },
    "0x7258997e": {
      "name": "NotActive",
      "types": [
        "uint256"
      ],
      "names": [
        "id"
      ]
    },
    "0x91beda24": {
      "name": "InsufficientAllowance",
      "types": [
        "address",
        "address",
        "uint256",
        "uint256"
      ],
      "names": [
        "owner",
        "spender",
        "have",
        "want"
      ]
    },
    "0x969bf728": {
      "name": "NothingToClaim",
      "types": [],
      "names": []
    },
    "0xbf8157f3": {
      "name": "BadTimeRange",
      "types": [
        "uint256",
        "uint256"
      ],
      "names": [
        "start",
        "stop"
      ]
    },
    "0xd92e233d": {
      "name": "ZeroAddress",
      "types": [],
      "names": []
    },
    "0xdb42144d": {
      "name": "InsufficientBalance",
      "types": [
        "address",
        "uint256",
        "uint256"
      ],
      "names": [
        "from",
        "have",
        "want"
      ]
    },
    "0xdd050eb2": {
      "name": "SelfStream",
      "types": [],
      "names": []
    },
    "0xe86f59ea": {
      "name": "TooSoon",
      "types": [
        "uint256"
      ],
      "names": [
        "availableAt"
      ]
    },
    "0xea8e4eb5": {
      "name": "NotAuthorized",
      "types": [],
      "names": []
    }
  },
  "agentHints": {
    "NotAuthorized": "This account is not allowed to do this right now. Check the permission or status intent to see who can.",
    "NothingToWithdraw": "Nothing has been earned since the last withdrawal. Try again later.",
    "InsufficientDeposit": "The account has less than that in the vault. Check get_vault, or withdraw with all: true.",
    "ZeroAmount": "The amount must be greater than zero.",
    "NothingToClaim": "Nothing is held for this account. Check with claim_held_payment and checkOnly, or get_stream's heldForClaim.",
    "NotActive": "This stream was already cancelled.",
    "NotFunded": "This deal was already released or refunded.",
    "NoSuchStream": "No stream has this id.",
    "NoSuchDeal": "No deal has this id.",
    "StartInPast": "The start time had already passed when the transaction ran. Use a larger startInSeconds.",
    "DeadlineInPast": "The deadline had already passed when the transaction ran. Use a larger deadlineSeconds.",
    "TokenTransferFailed": "The token transfer failed: check the agent's balance and allowance.",
    "OutOfGas": "The transaction used all its gas. Nothing changed on-chain. Retry it, or set a higher GAS_LIMIT."
  }
};
